CREATE SCHEMA IF NOT EXISTS FTE;

DROP TABLE IF EXISTS FTE.COUNTRY CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER_SEGMENT_TYPE CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER_CONTRACT CASCADE;



/*EXAMPLE DATABASE*/
CREATE TABLE FTE.COUNTRY (
	Country_Code SMALLINT NOT NULL PRIMARY KEY,
	Country_Name VARCHAR(30) NOT NULL
);

CREATE TABLE FTE.CUSTOMER_SEGMENT_TYPE (
	Customer_Segment_Code SMALLINT NOT NULL PRIMARY KEY,
	Customer_Segment_Desc VARCHAR(50) NOT NULL
);

CREATE TABLE FTE.CUSTOMER (
	Customer_Id INTEGER NOT NULL,
	Country_Code SMALLINT NOT NULL REFERENCES FTE.COUNTRY(Country_Code),
	Customer_Since DATE NOT NULL,
	Customer_Name VARCHAR(30) NOT NULL,
	Customer_Name_Since DATE NOT NULL,
	Customer_Segment_Code SMALLINT REFERENCES FTE.CUSTOMER_SEGMENT_TYPE(Customer_Segment_Code) NOT NULL,
	Customer_Segment_Since DATE NOT NULL,
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (Customer_Id, Country_Code)
);

CREATE TABLE FTE.CUSTOMER_CONTRACT (
	Customer_Id INTEGER NOT NULL,
	Country_Code SMALLINT NOT NULL REFERENCES FTE.COUNTRY(Country_Code),
	Contract_Nbr VARCHAR(35) NOT NULL,
	Customer_Contract_Since DATE NOT NULL,
	CONSTRAINT PK_CUST_CONTRACT PRIMARY KEY (Customer_Id, Country_Code, Contract_Nbr),
	FOREIGN KEY (Customer_Id, Country_Code) REFERENCES FTE.CUSTOMER (Customer_Id, Country_Code)
);

INSERT INTO FTE.COUNTRY (Country_Code, Country_Name)
VALUES (1, 'Estonia');
INSERT INTO FTE.COUNTRY (Country_Code, Country_Name)
VALUES (2, 'Latvia');
INSERT INTO FTE.COUNTRY (Country_Code, Country_Name)
VALUES (3, 'Lithuania');

INSERT INTO FTE.CUSTOMER_SEGMENT_TYPE (Customer_Segment_Code, Customer_Segment_Desc)
VALUES (1, 'New');
INSERT INTO FTE.CUSTOMER_SEGMENT_TYPE (Customer_Segment_Code, Customer_Segment_Desc)
VALUES (2, 'Regular buyer');
INSERT INTO FTE.CUSTOMER_SEGMENT_TYPE (Customer_Segment_Code, Customer_Segment_Desc)
VALUES (3, 'Idle');

DELETE FROM TEMPORAL.TEMPORAL_METADATA;
DROP TABLE IF EXISTS FTE.CUSTOMER_HIST CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER_NAME_HIST CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER_SEGMENT_HIST CASCADE;
DROP TABLE IF EXISTS FTE.CUSTOMER_CONTRACT_HIST CASCADE;

SELECT TEMPORAL.TEMPORALIZE ('FTE','CUSTOMER','Customer_Id, Country_Code','Customer_Since','CUSTOMER_HIST','CUSTOMER_VW');
SELECT TEMPORAL.TEMPORALIZE ('FTE','CUSTOMER','Customer_Name','Customer_Name_Since','CUSTOMER_NAME_HIST','CUSTOMER_NAME_VW');
SELECT TEMPORAL.TEMPORALIZE ('FTE','CUSTOMER','Customer_Segment_Code','Customer_Segment_Since','CUSTOMER_SEGMENT_HIST','CUSTOMER_SEGMENT_VW');
SELECT TEMPORAL.TEMPORALIZE ('FTE','CUSTOMER_CONTRACT','Customer_Id,Country_Code,Contract_Nbr','Customer_Contract_Since','CUSTOMER_CONTRACT_HIST','CUSTOMER_CONTRACT_VW');
